apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/postgres-nfs"
    server: 192.168.6.57
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
