apiVersion: v1
kind: PersistentVolume
metadata:
  name: bounadi-data-pv-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/bounadi-nfs
    server: 192.168.6.57
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bounadi-data-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi