apiVersion: v1
kind: Service
metadata:
  name: odoo-service-nfs
spec:
  type: NodePort
  selector:
    app: odoo-nfs
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30400
